"""The cases of the comprehension bench (docs/PIANO.md, block P1), picked by hand from Earnings-21
(Rev.com, CC BY-SA 4.0: real earnings calls, human transcripts). Each is a sentence of a real call,
by its index in the corpus' sentences (bench/comprehend.py cases rebuilds them, the same way), and
why a listener gets lost there. The references are written by hand, true as of 2020, when the calls
took place. cases.json quotes the corpus: like it, it is CC BY-SA 4.0
(Earnings-21 by Rev.com, https://github.com/revdotcom/speech-datasets).

Ways of getting lost (the pillar): "heard" didn't hear it (the card must give the sentence),
"asked" a question was put to you by name, "word" a word or expression you don't know (foreign or
jargon), "who" who or what something is, "meant" you got the words, not what they meant.
"""

# Didn't hear it: picked by bench/comprehend.py among the aligned sentences of these calls
# (10 to 35 words, not the operator), spread evenly: the reference is the sentence itself.
HEARD_FILES = ['4320211', '4341191', '4344338', '4344866', '4346818', '4359971', '4360674', '4364366',
               '4366302', '4368670', '4375653', '4397829']
HEARD_PER_FILE = 5

# A question put to you by name. [first sentence, last sentence] of it, the name, what you were asked.
# The listener is the one named; the same tap with a listener who isn't named is the control.
ASKED = [
    (185, 185, 'Brian', 'to restate the second part of your question'),
    (231, 231, 'Brian', 'how much of a headwind the conversion of the 42 California stores was to revenue from acquisitions this quarter'),
    (1280, 1280, 'Carolina', 'whether you want to add anything on managing liquidity versus leverage'),
    (1343, 1343, 'Carolina', 'whether you want to add anything to that answer'),
    (1913, 1914, 'Tom', 'why now is the right time for the CEO transition'),
    (2049, 2049, 'Tom', 'whether this segment will be down more than the company average'),
    (3354, 3354, 'Paul', 'to speak louder'),
    (3458, 3458, 'Camilo', 'to give more detail on what is going on in the markets of Central America and the Caribbean'),
    (3509, 3509, 'Tom', 'whether you want to add more detail to the answer'),
    (3514, 3514, 'Roberto', 'whether that answers your question'),
    (3661, 3661, 'Bill', 'to take this question: it is for you'),
    (3729, 3729, 'Carlos', 'to say something about working capital management'),
    (4302, 4303, 'Markus', 'about working capital and the risk to SME customers, as it pertains to sea freight'),
    (4920, 4920, 'Peter', 'how much of the 100 million euros of cost reductions is structural'),
    (5619, 5619, 'Alan', 'what your take is on the court system and on early, quick settlements'),
    (5972, 5972, 'Jim', 'what region of the country you are focused on'),
    (6261, 6261, 'Juan', 'to try to answer the very first question'),
    (7987, 7987, 'Joc', 'to review the basis for the countervailing duties position (from John Roberts of UBS)'),
    (8022, 8022, 'Joc', 'whether you have ramped up production at the mine with DAP prices up more than $50 a ton'),
    (8057, 8057, 'Joc', 'what savings you expect from sending K3 potash to the K1 mill'),
    (8074, 8074, 'Clint', 'to discuss that'),
    (8154, 8154, 'Joc', 'to talk about capital priorities, answering both questions'),
    (8617, 8617, 'Zach', 'whether that answer is responsive'),
    (8819, 8820, 'Tom', 'whether the 24 bonds being called means the deal is likely to close'),
    (9119, 9119, 'Craig', 'whether you want to add anything'),
    (9500, 9500, 'Rob', 'to talk about the current pipeline, on and off campus'),
    (9668, 9669, 'Todd', 'about NOI trending back to 3% against recent trends'),
    (9684, 9684, 'Chris', 'to take that question'),
    (10154, 10154, 'Jorge', 'whether July so far, in total dollars across the book, is similar to 2019'),
    (10336, 10337, 'Don', 'for an update on your integration efforts'),
    (10803, 10803, 'Robert', 'how important staying free-cash-flow positive is when deciding whether to go after the ducts'),
    (11419, 11419, 'Adi', 'whether you want to take this question or should he'),
    (11885, 11885, 'Markus', 'about the EU recovery fund and how RWE will benefit from it'),
    (12947, 12947, 'Sam', 'about the OPEX trajectory over the next 12 months to reach the 350 to 375 number'),
    (13143, 13143, 'Phil', 'whether that helps'),
    (13384, 13385, 'Ryan', 'how what has happened compares with the scenarios you laid out at the Strategy Day'),
    (14566, 14567, 'Tom', 'whether you got a new tier one customer in Q3, and who'),
    (14592, 14593, 'Mike', 'a modelling question on OPEX levels next year'),
    (14674, 14675, 'Tom', 'what percentage of total revenue tier three is today'),
    (15939, 15939, 'Paul', 'where you hope to have inventory at year end'),
    (16160, 16160, 'Matt', 'whether there are new wholesale opportunities once past the inventory constraints'),
    (16356, 16356, 'Steve', 'to take that one'),
    (17731, 17731, 'Steve', 'whether you gave guidance on how premises would grow in the fourth quarter'),
    (18410, 18410, 'Rell', 'what accrued tax rate to assume for fiscal 2021'),
]
# Named, but nobody is asking them anything: the card must not say "they asked you".
NAMED_NOT_ASKED = [(184, 'Brian'), (1968, 'Rainer'), (8150, 'John'), (8229, 'Ben'), (9442, 'Rob'), (10360, 'John'), (10508, 'Josh')]
CONTROL_NAME = 'Elena'

# A word or an expression you don't know (business English: jargon for a native too).
WORD = [
    (231, 'headwind', 'a factor pushing results down: here, how much the store conversions held back revenue'),
    (1558, 'cost out tailwind', 'the boost to results from cost cuts, which should grow during the year'),
    (106, 'basis points', 'hundredths of a percentage point: 20 basis points = 0.2 points (38% to 37.8%)'),
    (135, 'run rate', 'the yearly sales these stores should reach once fully integrated, at full speed'),
    (894, 'free cashflow', 'the cash left after running the business and paying for investments'),
    (11534, 'adjusted EBITDA', 'operating profit before interest, taxes, depreciation and amortisation, without one-off items'),
    (5817, 'accretion', 'the extra earnings per share that the Florida acquisitions add (15 and 20 cents)'),
    (11729, 'value accretive', 'something that adds value for shareholders'),
    (142, 'comparable store sales guidance', 'their forecast for sales in stores open for at least a year, compared with last year'),
    (18968, 'comp sales', 'sales in stores open for at least a year, compared with the year before'),
    (9291, 'same-store NOI', 'net operating income of the same buildings owned in both periods'),
    (9376, 'trailing 12 month', 'over the last twelve months'),
    (1169, 'provide a little bit of color', 'give more detail, explain more'),
    (19478, 'give us some color', 'give more detail'),
    (941, 'backlog', 'orders already received and not yet delivered or billed'),
    (4675, 'deleveraging', 'reducing debt compared with earnings'),
    (909, 'CapEx', 'capital expenditure: money spent on plants, equipment and other long-term assets'),
    (868, 'organically', 'not counting acquisitions, sales of businesses and currency effects'),
    (2634, 'cost synergy funnel', 'the list of savings found by combining the two companies (over $350 million)'),
    (2676, 'bolt-on M&A', 'small acquisitions that plug into businesses they already have'),
    (812, 'decremental margins', 'how much profit is lost for every dollar of sales lost'),
    (9344, 'cap rate', 'the yearly rental income of a building divided by its price: its yield (5 to 5.8%)'),
    (1062, 'utilization', 'how much the engines are used, i.e. how much airlines fly'),
    (2831, 'book-to-bill greater than one', 'more new orders came in than was billed: the order book is growing'),
    (796, 'liquidity', 'cash and credit available to pay what is due'),
    (900, 'mark to market', 'valuing the Baker Hughes stake at today\'s market price, booking the loss'),
    (7987, 'countervailing duties', 'extra import duties against goods whose producers get foreign subsidies (here phosphate from Morocco and Russia)'),
    (12872, 'top line', 'revenue (sales), the first line of the income statement'),
    (849, 'the bottom line is', 'the essential point is, in short'),
    (19247, 'flattish', 'roughly unchanged, about flat'),
    (12060, 'OPEX', 'operating expenses, the running costs'),
    (1085, 'a ramp', 'a gradual increase (in postponed procedures coming back)'),
    (19306, 'volume surcharges', 'extra fees carriers charge when shipping volumes peak'),
    (88, 'diluted / dilutive to earnings per share', 'the acquisitions lower earnings per share at first'),
    (139, 'financial covenant', 'a condition in the loan agreements, such as a maximum debt ratio'),
    (885, 'impairment', 'a write-down: the assets are now worth less on the books'),
    (9309, 'pent up demand', 'demand held back during lockdown that is now coming back'),
    (9398, 'contractual escalators', 'the yearly rent increases written into the leases (1.7%)'),
    (1810, 'down low single digits', 'fell by a few percent, about 1 to 3%'),
    (918, 'sequentially', 'compared with the previous quarter'),
    (9346, 'MOB rent rolls', 'the rents of medical office buildings, tenant by tenant'),
    (8022, 'DAP', 'diammonium phosphate, the most common phosphate fertiliser'),
    (2028, 'kaizens', 'short focused workshops to improve a process (lean method)'),
    (824, "I'm not going to sugar coat this", 'I won\'t make it sound better than it is'),
    (1575, "the growth isn't high calorie", 'the growth is not the profitable, high-margin kind'),
    (4707, 'ESG rating', 'a score of how the company does on environment, social and governance'),
    (1292, 'de-risk our balance sheet', 'reduce financial risk: less debt and fewer obligations'),
    (1369, 'furloughs', 'workers sent home temporarily, unpaid or partly paid, without being fired'),
    (1609, 'sit back', 'wait without doing anything'),
]

# Who or what is it: the public names the server may see (privacy option A).
WHO = [
    (12517, 'GRAIL', 'a US start-up, spun out of Illumina in 2016, developing a blood test that finds many cancers early'),
    (12528, 'Illumina', 'the US company that leads the market for DNA sequencing machines'),
    (12560, 'Galleri', 'GRAIL\'s blood test for detecting many types of cancer early'),
    (1772, 'Cytiva', 'GE\'s former biopharma business (equipment to make biological drugs and vaccines), bought by Danaher in 2020'),
    (1762, 'Cepheid', 'a Danaher company making rapid molecular diagnostic tests (GeneXpert)'),
    (1970, 'Videojet', 'a Danaher company making industrial printers that mark codes and dates on products and packaging'),
    (1968, 'Rainer', 'Rainer Blair, who is taking over from Tom Joyce as Danaher\'s CEO'),
    (879, 'Baker Hughes', 'an oil-field services company in which GE still holds a stake it is selling'),
    (5673, 'NextEra Energy Partners', 'a listed company controlled by NextEra that owns contracted wind, solar and pipeline assets and pays out their cash'),
    (11546, 'Nordex', 'a German wind turbine maker; RWE is buying its pipeline of wind and solar projects'),
    (11540, 'E.ON', 'the German energy group; in the swap RWE got its renewables and E.ON got Innogy\'s networks and retail'),
    (311, 'Amazon', 'the online retailer, which sells tyres online with fitting at partner garages such as Monro'),
    (18926, 'buybuy BABY', 'Bed Bath & Beyond\'s chain of baby-product stores'),
    (1767, 'Beckman Coulter', 'a Danaher company making laboratory diagnostic instruments and tests'),
    (1798, 'Radiometer', 'a Danaher company making blood-gas analysers used at the point of care'),
    (1760, 'IDT', 'Integrated DNA Technologies, a Danaher company making custom DNA (primers and probes) for tests and research'),
    (12640, 'BMS', 'Bristol Myers Squibb, a large US pharmaceutical company'),
    (1243, 'LEAP-1A', 'the CFM (GE and Safran) jet engine for the Airbus A320neo; the LEAP-1B is for the Boeing 737 MAX'),
    (885, 'GECAS', 'GE Capital Aviation Services, GE\'s aircraft leasing business'),
    (945, 'CFM 56', 'the previous-generation CFM (GE and Safran) engine on older Boeing 737s and Airbus A320s'),
    (1128, '737 MAX', 'Boeing\'s single-aisle plane, grounded since 2019 after two crashes; GE and Safran make its engines'),
    (9329, 'Mercy', 'a large US Catholic hospital system based in St. Louis, which bought buildings from the company for $244 million'),
    (9317, 'CMS', 'the US federal agency that runs Medicare and Medicaid'),
    (9286, 'PPP', 'the Paycheck Protection Program: 2020 US government loans to small businesses, forgiven if spent on payroll, rent and utilities'),
    (2653, 'Gardner Denver', 'the compressor and pump maker that merged with Ingersoll Rand\'s industrial business in 2020'),
    (2601, 'IRX', 'Ingersoll Rand Execution Excellence, the company\'s own management system'),
    (9278, 'HCA', 'HCA Healthcare, the largest US for-profit hospital operator'),
    (1812, 'DBS', 'the Danaher Business System, Danaher\'s own method of continuous improvement (lean)'),
    (19092, 'Instacart', 'a US app for same-day grocery delivery from stores'),
    (19093, 'Harmon Face Values', 'Bed Bath & Beyond\'s chain of health and beauty stores'),
    (5801, 'Mountain Valley Pipeline', 'a natural gas pipeline from West Virginia to Virginia, held up by permit disputes; NextEra owns a stake'),
    (5690, 'FPL', 'Florida Power & Light, NextEra\'s utility in Florida'),
    (5702, 'Gulf Power', 'the utility in north-west Florida that NextEra bought in 2019'),
    (7959, 'Esterhazy K3', 'Mosaic\'s new potash mine shafts at Esterhazy, Saskatchewan (Canada)'),
    (11885, 'EU recovery fund', 'the EU\'s €750 billion post-COVID recovery plan (Next Generation EU), with money for green investment'),
    (4707, 'MSCI', 'a company that publishes financial indexes and rates companies on ESG'),
    (254, 'Jefferies', 'a US investment bank, whose analyst is asking the question'),
    (12694, 'FDA', 'the US agency that authorises medicines and medical devices'),
    (9627, 'Cares Act', 'the US COVID relief law of March 2020, which gave money to hospitals and companies'),
    (5742, 'Dania Beach Clean Energy Center', 'a new natural-gas power plant FPL is building in Florida'),
]

# You got the words, not what they meant.
MEANT = [
    (1030, 'more to come, stay tuned', 'more cost cuts (likely job cuts) will be announced later'),
    (1028, 'right-size our function costs', 'cut costs and staff in head-office functions'),
    (1070, "right-sizing production capacity", 'cutting production (and probably jobs) because demand fell'),
    (1024, 'rationalize costs and reduce the size at corporate', 'cut costs, mostly jobs, at headquarters'),
    (2641, 'headcount actions', 'they have laid people off'),
    (1462, "we'll see how that plays out", 'he does not know and will not commit to how big the impact will be'),
    (2543, "we'll see how that plays out", 'he cannot say yet; it depends on how the gas market goes'),
    (1553, "too early to tell", 'he will not give a forecast now'),
    (1886, 'too early to really kind of tell', 'they will not forecast serology test volumes yet'),
    (12095, 'life would be easier if', 'nobody knows the answer yet; he cannot answer'),
    (1576, "they're not one-offs until they go away permanently", 'problems they call one-time may keep coming back: he does not accept the excuse'),
    (2047, "I wouldn't trade those businesses for any in their markets", 'he thinks they are the best businesses in their markets'),
    (3043, 'keep it at 250 just because we think it\'s prudent', 'they will probably beat 250 million but will not raise the target, so as not to over-promise'),
    (3047, 'be prudent from going out there and saying that the 250 will increase', 'savings will likely be higher than 250, but they will not promise it'),
    (4894, "it's a call that we have to make jointly with them", 'it is not only up to them: the customers decide too, so no answer now'),
    (8268, "we don't see significant upside", 'do not expect results much better than the forecast'),
    (8292, "I wouldn't say we see increased demand", 'demand is not growing, it is only coming back to normal'),
    (8303, "I wouldn't say we're actually forecasting an acceleration", 'they do not expect potash demand to speed up: he corrects the analyst'),
    (11789, 'we have a lot of moving parts', 'many things can still change, so he will not give a precise number'),
    (11961, "I wouldn't call that low, it's more medium", 'the profitability of those projects is modest; he softens it'),
    (12247, "we don't comment on rumors", 'he neither confirms nor denies the Humber deal'),
    (19330, "we're being prudent on that", 'their forecast is deliberately cautious, because shipping costs could hurt more'),
    (19337, "we want to make sure that we're being prudent", 'their outlook is deliberately low: it is only one month into the quarter'),
    (1201, "that's what we're comfortable sharing", 'they know more but will not say it'),
    (1610, "not gonna take the view that we've got a sharp V bounce coming", 'they expect a slow recovery, so they are cutting costs now'),
    (1267, 'changes on a more permanent basis', 'some cuts that looked temporary will become permanent (jobs included)'),
    (4967, 'a little cautious until we see the pace of the ramp', 'they will not commit to numbers until they see how fast customers restart'),
    (9523, "I'm not sure if I'm overly reading into your commentary", 'the analyst wants them to confirm the pipeline is bigger than before, without saying it'),
    (1582, "we've got work to do", 'they are not there yet: that business is still not good enough'),
    (1111, 'largely about improving execution', 'renewables did badly because of their own mistakes, not because of COVID'),
    (19397, 'some softness', 'sales fell (in cleaning, for example)'),
    (27, 'not satisfied with our financial results', 'the results this quarter were bad'),
    (5932, 'that kind of transcends politics', 'whoever wins the election, renewables will keep growing'),
    (6005, "I'd be disappointed if we don't make some kind of pilot investment", 'they will very probably invest in a pilot next year'),
    (12151, "it's always good to be honest", 'he admits there are gaps in their pipeline'),
    (184, "we certainly don't like talking about the weather", 'the weather did hurt tyre sales: he blames it while saying he does not want to make excuses'),
    (2644, 'to remain prudent', 'they will not raise the savings target for now, although it may be beaten'),
    (2667, 'remained very prudent on preserving liquidity', 'they are hoarding cash because times are uncertain'),
]

LISTENERS = {'it-B2': {'native': 'it', 'level': 'B2', 'label': 'Italian, English B2'},
             'en-C2': {'native': 'en', 'level': 'C2', 'label': 'native English speaker'}}
